[package]
name = "advent_of_rust_22"
version = "0.1.0"
edition = "2021"
authors = ["Zhengyi Chen"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

